services:
  postgres:
    image: postgres:16
    container_name: ai-support-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-incident_db}
      POSTGRES_USER: ${POSTGRES_USER:-incident_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: