spring.application.name=incident-service
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_db
spring.datasource.username=${POSTGRES_USER:incident_user}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8081

management.endpoints.web.exposure.include=health,info